name: Build and Push to ECR
on:
  push:
    paths:
      - 'application/**'
      - '.github/workflows/docker-build.yml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-push-service1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::539935451710:role/bayer-nsh-github-oidc-role
          role-session-name: github-assume
          aws-region: us-west-1

      - name: Login to Amazon ECR # login ecr
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image for Service1
        run: |
          docker build -t ${{ vars.ECR_REGISTRY }}/test-repo-1:${{ github.sha }} ./application/appointments
          docker tag ${{ vars.ECR_REGISTRY }}/test-repo-1:${{ github.sha }} ${{ vars.ECR_REGISTRY }}/test-repo-1:latest

      - name: Push Docker Image for Service1
        run: |
          docker push ${{ vars.ECR_REGISTRY }}/test-repo-1:${{ github.sha }}
          docker push ${{ vars.ECR_REGISTRY }}/test-repo-1:latest
          
  build-push-service2:
    runs-on: ubuntu-latest
    needs: build-push-service1  ### Optional dependency
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::539935451710:role/bayer-nsh-github-oidc-role
          role-session-name: github-assume
          aws-region: us-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image for Service2
        run: |
          docker build -t ${{ vars.ECR_REGISTRY }}/test-repo-2:${{ github.sha }} ./application/patient
          docker tag ${{ vars.ECR_REGISTRY }}/test-repo-2:${{ github.sha }} ${{ vars.ECR_REGISTRY }}/test-repo-2:latest
          
      - name: Push Docker Image for Service2
        run: |
          docker push ${{ vars.ECR_REGISTRY }}/test-repo-2:${{ github.sha }}
          docker push ${{ vars.ECR_REGISTRY }}/test-repo-2:latest

   

